const lessons = {
  number: { category: 'Foundations', title: 'Number', intro: 'Build fluency with the number skills that support every GCSE topic.', steps: ['Read the question carefully and identify the operation or relationship needed.', 'Estimate the answer first so you can check whether your final result is sensible.', 'Work accurately with fractions, decimals, factors, primes, and order of operations.', 'Check your answer using an inverse operation or a second method.'], example: 'Work out 3/4 + 0.2', answer: '3/4 = 0.75, so 0.75 + 0.2 = 0.95', practice: 'Work out 2.5 x 0.4.', practiceAnswer: '1', },
  algebra: { category: 'Expressions and symbols', title: 'Algebra', intro: 'Use letters to represent unknown values and describe patterns clearly.', steps: ['Identify the variable and what it represents.', 'Simplify like terms by collecting terms with the same variable and power.', 'Substitute known values carefully, using brackets for negative numbers.', 'Check by putting your result back into the original expression.'], example: 'Simplify 4x + 3 - x + 5', answer: 'Collect like terms: 4x - x = 3x and 3 + 5 = 8, so the answer is 3x + 8.', practice: 'Simplify 7a - 2 + 3a + 9.', practiceAnswer: '10a + 7', },
  equations: { category: 'Algebra', title: 'Equations', intro: 'Solve equations by keeping both sides balanced while you isolate the unknown.', steps: ['Simplify each side if needed.', 'Undo addition or subtraction first.', 'Undo multiplication or division next.', 'Substitute your answer back to check both sides match.'], example: 'Solve 3x + 7 = 25', answer: 'Subtract 7: 3x = 18. Divide by 3: x = 6.', practice: 'Solve 5x - 4 = 21.', practiceAnswer: 'x = 5', },
  inequalities: { category: 'Algebra', title: 'Inequalities', intro: 'Describe a range of possible values rather than one exact answer.', steps: ['Solve the inequality like an equation.', 'Reverse the inequality sign when multiplying or dividing by a negative.', 'Show the solution on a number line with an open or closed circle.', 'Test one value from your region to check it works.'], example: 'Solve 2x + 1 < 9', answer: '2x < 8, so x < 4. The circle at 4 is open.', practice: 'Solve 3x - 2 >= 10.', practiceAnswer: 'x >= 4', },
  ratio: { category: 'Proportion', title: 'Ratio and Proportion', intro: 'Compare quantities and scale relationships without losing the connection between them.', steps: ['Make sure all quantities use the same units.', 'Simplify the ratio by dividing each part by the highest common factor.', 'Use the scale factor to move from a ratio to actual amounts.', 'Check that the total parts add to the whole.'], example: 'Share 35 in the ratio 2:5', answer: 'There are 7 parts. Each part is 5, so the shares are 10 and 25.', practice: 'Share 48 in the ratio 1:3.', practiceAnswer: '12 and 36', },
  percentages: { category: 'Everyday maths', title: 'Percentages', intro: 'Use percentages to compare amounts, calculate change, and solve real-world problems.', steps: ['Convert the percentage to a decimal multiplier when useful.', 'For an increase, use 1 + the percentage as a decimal.', 'For a decrease, use 1 - the percentage as a decimal.', 'Round only at the end and check whether the result should be larger or smaller.'], example: 'Increase 80 by 15%', answer: 'The multiplier is 1.15. 80 x 1.15 = 92.', practice: 'Decrease 240 by 25%.', practiceAnswer: '180', },
  sequences: { category: 'Patterns', title: 'Sequences', intro: 'Find the rule connecting terms and use it to predict any position in the sequence.', steps: ['Find the common difference for a linear sequence.', 'Use the first term and difference to form an nth-term rule.', 'Substitute the requested position into the rule.', 'Check the rule generates the first few terms.'], example: 'Find the nth term of 5, 8, 11, 14...', answer: 'The difference is 3. The nth term is 3n + 2.', practice: 'Find the nth term of 4, 9, 14, 19...', practiceAnswer: '5n - 1', },
  graphs: { category: 'Representing maths', title: 'Graphs', intro: 'Turn equations into pictures so you can see relationships, intersections, and change.', steps: ['Choose a sensible scale for each axis.', 'Make a table of values from the equation.', 'Plot coordinates carefully and label the axes.', 'Join points smoothly only when the relationship is continuous.'], example: 'Plot y = 2x + 1 for x = 0, 1, 2', answer: 'The points are (0, 1), (1, 3), and (2, 5).', practice: 'What is the y-intercept of y = 4x - 3?', practiceAnswer: '-3', },
  coordinates: { category: 'Graphs', title: 'Coordinates', intro: 'Locate points and describe lines precisely on a coordinate grid.', steps: ['Read the x-coordinate first, then the y-coordinate.', 'Use gradient = change in y / change in x.', 'Use the midpoint formula by averaging both coordinates.', 'Keep negative signs visible when working in different quadrants.'], example: 'Find the midpoint of (2, 4) and (8, 10)', answer: 'Average the coordinates: ((2 + 8)/2, (4 + 10)/2) = (5, 7).', practice: 'Find the gradient between (1, 2) and (5, 10).', practiceAnswer: '2', },
  geometry: { category: 'Space and shape', title: 'Geometry', intro: 'Use angle facts and properties of shapes to build reliable geometric arguments.', steps: ['Mark the information given in the diagram.', 'Choose the angle fact that connects the known and unknown angles.', 'Write a clear equation before calculating.', 'State the reason for each important step.'], example: 'Two angles in a triangle are 45 and 65. Find the third.', answer: 'Angles in a triangle total 180, so the third angle is 180 - 45 - 65 = 70 degrees.', practice: 'Find the missing angle in a straight line if one angle is 127 degrees.', practiceAnswer: '53 degrees', },
  transformations: { category: 'Space and shape', title: 'Transformations', intro: 'Move and resize shapes using precise rules on a coordinate grid.', steps: ['Identify whether the transformation is a translation, reflection, rotation, or enlargement.', 'For a translation, write the vector; for a rotation, give the centre and angle.', 'Track one point first, then apply the same rule to the whole shape.', 'Check lengths, angles, or parallel sides that should remain unchanged.'], example: 'Translate (2, 1) by the vector (3, -2)', answer: 'Add the vector: (2 + 3, 1 - 2) = (5, -1).', practice: 'Reflect (4, -2) in the x-axis.', practiceAnswer: '(4, 2)', },
  pythagoras: { category: 'Right-angled triangles', title: 'Pythagoras', intro: 'Find a missing side in a right-angled triangle using a squared relationship.', steps: ['Identify the right angle and the hypotenuse opposite it.', 'Use a² + b² = c² with c as the hypotenuse.', 'Rearrange before substituting if the missing side is not c.', 'Square root the final value and include suitable units.'], example: 'Find the hypotenuse when the shorter sides are 6 and 8.', answer: 'c² = 6² + 8² = 100, so c = 10.', practice: 'Find the hypotenuse when the shorter sides are 5 and 12.', practiceAnswer: '13', },
  trigonometry: { category: 'Right-angled triangles', title: 'Trigonometry', intro: 'Use SOHCAHTOA to connect angles and sides in right-angled triangles.', steps: ['Label the opposite, adjacent, and hypotenuse sides relative to the known angle.', 'Choose sin, cos, or tan from SOHCAHTOA.', 'Substitute the values and use the inverse trig function for an angle.', 'Check your calculator is in degree mode.'], example: 'Find the opposite side when angle = 30 degrees and hypotenuse = 10.', answer: 'sin(30) = opposite / 10, so opposite = 10 x 0.5 = 5.', practice: 'Find the angle when opposite = 6 and hypotenuse = 10.', practiceAnswer: '36.9 degrees (to 1 decimal place)', },
  'circle-theorems': { category: 'Circles', title: 'Circle Theorems', intro: 'Use fixed angle relationships to solve problems involving chords, arcs, and tangents.', steps: ['Mark the angles and radii shown in the diagram.', 'Look for a centre, circumference, tangent, or cyclic quadrilateral.', 'Apply the matching theorem and write the reason.', 'Use angle totals to finish the calculation.'], example: 'An angle at the centre is 84 degrees. Find the angle at the circumference on the same arc.', answer: 'The angle at the circumference is half the angle at the centre: 84 / 2 = 42 degrees.', practice: 'What is the angle between a tangent and radius at the point of contact?', practiceAnswer: '90 degrees', },
  vectors: { category: 'Geometry', title: 'Vectors', intro: 'Describe direction and movement with mathematical arrows.', steps: ['Treat a vector as a movement from one point to another.', 'Add vectors by adding corresponding components.', 'Use a negative vector for the opposite direction.', 'For proofs, express both paths using the same vector terms.'], example: 'If a = (2, 3) and b = (4, -1), find a + b.', answer: 'Add components: a + b = (2 + 4, 3 - 1) = (6, 2).', practice: 'Find 2(3, -4).', practiceAnswer: '(6, -8)', },
  'area-volume': { category: 'Measures', title: 'Area and Volume', intro: 'Measure flat shapes and solid objects by choosing the right formula and units.', steps: ['Identify the shape and write the correct formula.', 'Substitute lengths with matching units.', 'For volume, remember the answer uses cubic units.', 'Estimate the size first to catch calculator errors.'], example: 'Find the area of a triangle with base 8 cm and height 5 cm.', answer: 'Area = 1/2 x 8 x 5 = 20 cm².', practice: 'Find the volume of a cuboid measuring 3 cm by 4 cm by 5 cm.', practiceAnswer: '60 cm³', },
  measures: { category: 'Measures', title: 'Measures', intro: 'Choose sensible units, convert accurately, and give answers to an appropriate precision.', steps: ['Write down the units in the question and answer.', 'Convert before calculating if the units do not match.', 'Use standard form for very large or very small values.', 'Round only as the question requests.'], example: 'Convert 2.4 metres into centimetres.', answer: '1 metre is 100 centimetres, so 2.4 m = 240 cm.', practice: 'Convert 3.5 kilograms into grams.', practiceAnswer: '3500 g', },
  probability: { category: 'Chance and risk', title: 'Probability', intro: 'Measure how likely events are and represent outcomes systematically.', steps: ['List all equally likely outcomes where possible.', 'Use probability = favourable outcomes / total outcomes.', 'For independent events, multiply probabilities along a branch.', 'Check every probability is between 0 and 1.'], example: 'What is the probability of rolling an even number on a fair die?', answer: 'There are 3 even outcomes out of 6, so 3/6 = 1/2.', practice: 'What is the probability of rolling a number greater than 4 on a fair die?', practiceAnswer: '1/3', },
  statistics: { category: 'Data and evidence', title: 'Statistics', intro: 'Summarise, compare, and interpret data without being misled by a graph.', steps: ['Identify the type of data and the most useful average.', 'Calculate the mean, median, mode, or range carefully.', 'Read scales and labels before comparing distributions.', 'Use the shape and spread of the data in your conclusion.'], example: 'Find the mean of 4, 7, 8, 11.', answer: 'Add the values to get 30, then divide by 4: mean = 7.5.', practice: 'Find the median of 3, 9, 4, 7, 12.', practiceAnswer: '7', },
  sampling: { category: 'Data and evidence', title: 'Sampling', intro: 'Learn how data is collected and how a sample can represent a wider population.', steps: ['Define the population you want to understand.', 'Choose a sample method that limits bias.', 'Make the sample large and varied enough for the question.', 'State limits when using a sample to predict the population.'], example: 'Why might a random sample be useful?', answer: 'It gives every member of the population a fair chance of selection, reducing selection bias.', practice: 'Name one risk of asking only your friends about a survey topic.', practiceAnswer: 'The sample may be biased because your friends may not represent the whole population.', },
  'financial-maths': { category: 'Everyday maths', title: 'Financial Maths', intro: 'Use percentages and arithmetic to make sense of money in real situations.', steps: ['Write down the original amount and the change.', 'Choose a multiplier for discounts, tax, or interest.', 'Keep money calculations accurate to two decimal places.', 'Check that the final amount makes sense in context.'], example: 'A £60 item has a 20% discount. Find the sale price.', answer: 'Pay 80%: £60 x 0.8 = £48.', practice: 'Find the simple interest on £500 at 4% for one year.', practiceAnswer: '£20', },
  indices: { category: 'Number', title: 'Indices and Surds', intro: 'Work with powers and exact roots using rules that keep expressions manageable.', steps: ['Apply index laws to powers with the same base.', 'Use negative indices to represent reciprocals.', 'Simplify square roots by taking out square factors.', 'Keep exact answers as surds unless a decimal is requested.'], example: 'Simplify 2³ × 2⁴.', answer: 'Add the powers: 2³ × 2⁴ = 2⁷ = 128.', practice: 'Simplify sqrt(50).', practiceAnswer: '5sqrt(2)', },
  quadratics: { category: 'Algebra', title: 'Quadratics', intro: 'Solve and interpret equations with a squared term and understand their parabolic graphs.', steps: ['Put the equation equal to zero.', 'Try factorising first, then use completing the square or the quadratic formula.', 'Check both roots in the original equation.', 'Use the graph to interpret roots, turning points, and intersections.'], example: 'Solve x² - 5x + 6 = 0.', answer: 'Factorise: (x - 2)(x - 3) = 0, so x = 2 or x = 3.', practice: 'Solve x² - 9 = 0.', practiceAnswer: 'x = 3 or x = -3', },
  proof: { category: 'Reasoning', title: 'Proof', intro: 'Explain why a mathematical statement must be true, not just why it works once.', steps: ['Start with a general variable or the information given.', 'Use valid algebraic or geometric facts at each step.', 'Avoid relying on one example as proof.', 'Finish with a clear statement that the result is always true.'], example: 'Prove the sum of two odd numbers is even.', answer: 'Let the odd numbers be 2a + 1 and 2b + 1. Their sum is 2a + 2b + 2 = 2(a + b + 1), which is even.', practice: 'Is one example enough to prove a statement for every number?', practiceAnswer: 'No. A proof must use a general argument.', },
};

const deepDives = {
  number: ['Use prime factorisation to find highest common factors and lowest common multiples efficiently.', 'Convert recurring decimals to fractions by using algebra when an exact answer is required.', 'Use bounds when values have been rounded: a value rounded to the nearest unit is within half a unit either side.', 'Keep fractions exact until the final step; premature decimals can create rounding errors.'],
  algebra: ['Expand brackets carefully, including negative signs and double brackets such as (x + 3)(x - 2).', 'Factorising reverses expansion: look first for a common factor, then for quadratics and difference of two squares.', 'When substituting a negative value, put it in brackets before applying powers or multiplication.', 'Algebraic fractions can be simplified by factorising the numerator and denominator before cancelling common factors.'],
  equations: ['The balance method works because the same operation must be applied to both sides of an equation.', 'For equations with fractions, multiply every term by the lowest common denominator before solving.', 'For simultaneous equations, eliminate one variable by adding or subtracting equations, or substitute one into the other.', 'Check solutions in the original equation, especially after squaring both sides or clearing fractions.'],
  inequalities: ['The solution set contains many values, so use a variable statement and a number-line diagram together.', 'An open circle represents < or >; a closed circle represents <= or >=.', 'Reversing the sign when dividing by a negative is essential: -2x > 6 becomes x < -3.', 'For two inequalities, look for the overlap; for an OR statement, combine both regions.'],
  ratio: ['A ratio compares parts, while a fraction of an amount compares one part with a whole.', 'For a shared total, add the ratio parts first, then divide the total by that number of parts.', 'Use a scale factor for maps, recipes, similar shapes, and best-buy questions.', 'In direct proportion, doubling one quantity doubles the other; in inverse proportion, their product stays constant.'],
  percentages: ['A percentage change is not the same as percentage points; always identify the original amount.', 'Successive percentage changes multiply, so a 10% increase followed by 10% decrease is not no change.', 'Reverse percentage questions require division by the multiplier, not subtraction of the percentage.', 'Compound interest and repeated growth use powers of the multiplier: original × multiplier raised to the number of periods.'],
  sequences: ['The first difference identifies a linear sequence; constant second differences identify a quadratic sequence.', 'For a linear nth term, the coefficient of n is the common difference.', 'A recurrence relation gives the next term from the previous one, so state the starting term too.', 'A sequence can be geometric when each term is multiplied by a constant ratio rather than increased by a constant difference.'],
  graphs: ['The gradient describes rate of change and the y-intercept is the value when x = 0.', 'A quadratic graph has a line of symmetry through its turning point; roots are where it crosses the x-axis.', 'Use graph intersections to solve equations involving two relationships.', 'Label scales clearly and do not join separate discrete values unless the context makes them continuous.'],
  coordinates: ['Gradient is rise over run, so keep the order of the points consistent in both numerator and denominator.', 'Parallel lines have equal gradients; perpendicular lines have gradients whose product is -1.', 'The equation y = mx + c gives the gradient m and y-intercept c directly.', 'For a perpendicular bisector, find the midpoint and use the negative reciprocal gradient.'],
  geometry: ['Angles on a straight line total 180 degrees, angles around a point total 360 degrees, and vertically opposite angles are equal.', 'Parallel lines create equal corresponding and alternate angles, with co-interior angles adding to 180 degrees.', 'Interior angles of an n-sided polygon total (n - 2) x 180 degrees.', 'A proof should name the angle fact used, not just write a sequence of unexplained numbers.'],
  transformations: ['Translations move every point by the same vector and preserve size, angles, and orientation.', 'Reflections use a mirror line; points stay the same perpendicular distance from that line.', 'Rotations need a centre, angle, and direction; use tracing or coordinates to avoid guessing.', 'An enlargement needs a scale factor and centre; a negative scale factor places the image on the opposite side of the centre.'],
  pythagoras: ['Pythagoras only applies to right-angled triangles, and the hypotenuse is always opposite the right angle.', 'For a shorter side, subtract the known squared sides before taking the square root.', 'A converse proof can show a triangle is right-angled by checking whether a² + b² = c².', 'Keep units consistent and remember that squared lengths produce square units before the final square root.'],
  trigonometry: ['SOHCAHTOA applies to right-angled triangles; label the sides from the chosen angle, not from the page orientation.', 'Use inverse sin, cos, or tan when the unknown is an angle.', 'For non-right-angled triangles, the sine rule and cosine rule extend the same ideas.', 'Draw a quick sketch and estimate the angle before using the calculator to catch an incorrect ratio.'],
  'circle-theorems': ['The angle at the centre is twice the angle at the circumference standing on the same arc.', 'Angles in the same segment are equal, and opposite angles in a cyclic quadrilateral sum to 180 degrees.', 'A tangent meets a radius at 90 degrees, and the tangent-chord theorem links a tangent angle to the alternate segment.', 'Mark equal radii and use isosceles triangle facts when a diagram contains the centre.'],
  vectors: ['A column vector shows horizontal movement above vertical movement; signs indicate direction.', 'A vector can be multiplied by a scalar, which changes its length and may reverse its direction.', 'The vector from A to B is position vector of B minus position vector of A.', 'For geometric proofs, show two routes between the same points and prove their vector expressions are equal.'],
  'area-volume': ['Area measures a surface in square units; volume measures space in cubic units.', 'For compound shapes, split the figure into familiar pieces and add or subtract their areas.', 'Surface area includes every exposed face, so draw a net or list each face before calculating.', 'A prism has volume equal to cross-sectional area multiplied by length.'],
  measures: ['Metric conversions scale by powers of ten: moving from metres to centimetres multiplies by 100.', 'Standard form is a × 10ⁿ where 1 <= a < 10; count the place-value moves carefully.', 'Upper and lower bounds depend on the rounding instruction and can be used to find a maximum possible error.', 'Use significant figures for measurement data and decimal places when the question specifies a fixed number of places.'],
  probability: ['The probabilities of all mutually exclusive outcomes add to 1.', 'For AND events, multiply along branches; for OR events, add mutually exclusive branches.', 'Conditional probability changes the sample space after information is given.', 'Use tree diagrams or two-way tables to avoid counting the same outcome twice.'],
  statistics: ['The mean uses every value but is sensitive to outliers; the median is often more representative for skewed data.', 'The interquartile range measures the spread of the middle half and is less affected by extreme values.', 'A misleading graph can use a truncated axis or unequal intervals, so inspect scales before interpreting it.', 'Correlation does not prove causation; a scatter graph can show association without explaining why it occurs.'],
  sampling: ['A simple random sample reduces selection bias, while systematic sampling selects at regular intervals.', 'Stratified sampling keeps subgroup proportions similar to the population.', 'A voluntary response sample can overrepresent people with strong opinions.', 'A larger random sample usually gives a more reliable estimate, but it cannot remove a biased question or method.'],
  'financial-maths': ['Simple interest is calculated from the original principal each time; compound interest adds interest to the growing balance.', 'Profit is selling price minus cost price, while percentage profit divides profit by cost price.', 'Use exchange-rate units carefully and state which currency is being converted from and to.', 'A recurring payment, tax, or depreciation problem can often be modelled with a percentage multiplier.'],
  indices: ['When multiplying powers with the same base, add indices; when dividing, subtract them; for a power of a power, multiply them.', 'A zero index gives 1 for any non-zero base, while a negative index gives a reciprocal.', 'Simplify surds by taking out the largest square factor, then rationalise denominators when required.', 'Keep exact surd answers until the final line so rounding does not alter the result.'],
  quadratics: ['The graph of y = ax² + bx + c opens up when a is positive and down when a is negative.', 'Factorising is quickest when the roots are integers; otherwise use completing the square or the quadratic formula.', 'The discriminant b² - 4ac tells you whether there are two, one, or no real roots.', 'The turning point can be found by completing the square or using x = -b/(2a).'],
  proof: ['A counterexample disproves a universal claim, but one successful example cannot prove one.', 'Use even numbers as 2n and odd numbers as 2n + 1 for general algebraic proofs.', 'For divisibility, finish with a visible factor such as 3k or 5k where k is an integer.', 'Write reasons in a logical order so every line follows from the previous one.'],
};

const topic = new URLSearchParams(window.location.search).get('topic') || 'number';
const lesson = lessons[topic] || lessons.number;

document.title = `${lesson.title} | Advanced Maths for GCSE`;
document.querySelector('#lesson-category').textContent = lesson.category;
document.querySelector('#lesson-title').textContent = lesson.title;
document.querySelector('#lesson-intro').textContent = lesson.intro;
document.querySelector('#steps-list').innerHTML = lesson.steps.map((step) => `<li>${step}</li>`).join('');
document.querySelector('#deep-dive-list').innerHTML = (deepDives[topic] || deepDives.number).map((idea) => `<li>${idea}</li>`).join('');
document.querySelector('#example-question').textContent = lesson.example;
document.querySelector('#example-answer').textContent = lesson.answer;
document.querySelector('#practice-question').textContent = lesson.practice;
document.querySelector('#practice-answer').textContent = lesson.practiceAnswer;

const videoSearches = [
  ['Watch an explanation', `${lesson.title} GCSE maths explained`],
  ['See worked examples', `${lesson.title} GCSE maths worked examples`],
  ['Practise exam questions', `${lesson.title} GCSE maths exam questions`],
];

document.querySelector('#video-links').innerHTML = videoSearches.map(([label, query]) => {
  const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;
  return `<a class="video-link" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
}).join('');
